name: unit_convert
description: A tiny and purely Dart written unit converter to convert between various units easily.
version: 0.1.0
homepage: https://github.com/bnxm/unit_convert

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.15.7
